// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk01xmzACeQFjrQOJJRZbw8hM3alSG0lY',
    appId: '1:14783158840:web:78ff40eebf96594ec7a4cd',
    messagingSenderId: '14783158840',
    projectId: 'kamus2-3a07c',
    authDomain: 'kamus2-3a07c.firebaseapp.com',
    databaseURL: 'https://kamus2-3a07c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kamus2-3a07c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn3im9_d7EgCwT1iPlDZXQEfXTYQYSsus',
    appId: '1:14783158840:android:ed57e97d2c75a504c7a4cd',
    messagingSenderId: '14783158840',
    projectId: 'kamus2-3a07c',
    databaseURL: 'https://kamus2-3a07c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kamus2-3a07c.appspot.com',
  );
}
